const ACTIVE_DEFENSE = 'Status_ACTIVE_DEFENSE';
const BLIND = 'Status_BLIND';
const CHALLENGE = 'Status_CHALLENGE';
const CHARMED =  'Status_CHARMED';
const CONSUME = 'Status_CONSUME';
const DAMAGE = 'Status_DAMAGE';
const DAMAGE_ON_MOVE = 'Status_DAMAGE_ON_MOVE';
const DEACTIVATED = 'Status_DEACTIVATED';
const DECAYING_TOUCH = 'Status_DECAYING_TOUCH';
const DEMONIC_BARGAIN = 'Status_DEMONIC_BARGAIN';
const DISARMED = 'Status_DISARMED';
const EFFECT = 'Status_EFFECT';
const EXTRA_TURN = 'Status_EXTRA_TURN';
const FEAR = 'Status_FEAR';
const FLOATING = 'Status_FLOATING';
const GUARDIAN_ANGEL = 'Status_GUARDIAN_ANGEL';
const HEAL = 'Status_HEAL';
const HEALING = 'Status_HEALING';
const HEAL_SHARING = 'Status_HEAL_SHARING';
const HEAL_SHARING_CASTER = 'Status_HEAL_SHARING_CASTER';
const INCAPACITATED = 'Status_INCAPACITATED';
const INVISIBLE = 'Status_INVISIBLE';
const KNOCKED_DOWN = 'Status_KNOCKED_DOWN';
const MUTED = 'Status_MUTED';
const PLAY_DEAD = 'Status_PLAY_DEAD';
const POLYMORPHED = 'Status_POLYMORPHED';
const SPARK = 'Status_SPARK';
const STANCE = 'Status_STANCE';
const THROWN = 'Status_THROWN';

const STATUS_TYPES = {
	ACTIVE_DEFENSE,
	BLIND,
	CHALLENGE,
	CHARMED,
	CONSUME,
	DAMAGE,
	DAMAGE_ON_MOVE,
	DEACTIVATED,
	DECAYING_TOUCH,
	DEMONIC_BARGAIN,
	DISARMED,
	EFFECT,
	EXTRA_TURN,
	FEAR,
	FLOATING,
	GUARDIAN_ANGEL,
	HEAL,
	HEALING,
	HEAL_SHARING,
	HEAL_SHARING_CASTER,
	INCAPACITATED,
	INVISIBLE,
	KNOCKED_DOWN,
	MUTED,
	PLAY_DEAD,
	POLYMORPHED,
	SPARK,
	STANCE,
	THROWN,
};

const types = Object.values(STATUS_TYPES);

function isStatusType(value) {
	return types.includes(value);
}

module.exports = {
	STATUS_TYPES,
	isStatusType,
};