const SKILL_FIELD_NAMES = {
  'NAME':'Name',
  'USING':'Using',
  'SKILLTYPE':'SkillType',
  'LEVEL':'Level',
  'FORGAMEMASTER':'ForGameMaster',
  'ISENEMYSKILL':'IsEnemySkill',
  'ABILITY':'Ability',
  'TIER':'Tier',
  'REQUIREMENT':'Requirement',
  'ACTIONPOINTS':'ActionPoints',
  'COOLDOWN':'Cooldown',
  'AIFLAGS':'AIFlags',
  'DAMAGE':'Damage',
  'DAMAGEMULTIPLIER':'Damage Multiplier',
  'DAMAGERANGE':'Damage Range',
  'DAMAGETYPE':'DamageType',
  'SKILLPROPERTIES':'SkillProperties',
  'TARGETRADIUS':'TargetRadius',
  'ADDRANGEFROMABILITY':'AddRangeFromAbility',
  'AREARADIUS':'AreaRadius',
  'DEATHTYPE':'DeathType',
  'EXPLODERADIUS':'ExplodeRadius',
  'CANTARGETCHARACTERS':'CanTargetCharacters',
  'CANTARGETITEMS':'CanTargetItems',
  'CANTARGETTERRAIN':'CanTargetTerrain',
  'FORCETARGET':'ForceTarget',
  'AMOUNTOFTARGETS':'AmountOfTargets',
  'AUTOAIM':'AutoAim',
  'TARGETCONDITIONS':'TargetConditions',
  'FORKINGCONDITIONS':'ForkingConditions',
  'USECHARACTERSTATS':'UseCharacterStats',
  'USEWEAPONDAMAGE':'UseWeaponDamage',
  'USEWEAPONPROPERTIES':'UseWeaponProperties',
  'PROJECTILECOUNT':'ProjectileCount',
  'PROJECTILEDELAY':'ProjectileDelay',
  'ANGLE':'Angle',
  'TEMPLATE':'Template',
  'IGNOREVISIONBLOCK':'IgnoreVisionBlock',
  'TEMPLATECHECK':'TemplateCheck',
  'CHANCETOPIERCE':'ChanceToPierce',
  'MAXPIERCECOUNT':'MaxPierceCount',
  'MAXFORKCOUNT':'MaxForkCount',
  'FORKLEVELS':'ForkLevels',
  'FORKCHANCE':'ForkChance',
  'ICON':'Icon',
  'DISPLAYNAME':'DisplayName',
  'DESCRIPTION':'Description',
  'STATSDESCRIPTION':'StatsDescription',
  'STATSDESCRIPTIONPARAMS':'StatsDescriptionParams',
  'PREPAREANIMATIONINIT':'PrepareAnimationInit',
  'PREPAREANIMATIONLOOP':'PrepareAnimationLoop',
  'PREPAREEFFECT':'PrepareEffect',
  'CASTANIMATION':'CastAnimation',
  'CASTANIMATIONCHECK':'CastAnimationCheck',
  'CASTTEXTEVENT':'CastTextEvent',
  'CASTEFFECT':'CastEffect',
  'PREVIEWEFFECT':'PreviewEffect',
  'REQUIREMENTS':'Requirements',
  'MEMORIZATIONREQUIREMENTS':'MemorizationRequirements',
  'MEMORYCOST':'Memory Cost',
  'MAGICCOST':'Magic Cost',
  'DIVIDEDAMAGE':'DivideDamage',
  'PROJECTILETERRAINOFFSET':'ProjectileTerrainOffset',
  'MOVINGOBJECT':'MovingObject',
  'PROJECTILETYPE':'ProjectileType',
  'OVERRIDEMINAP':'OverrideMinAP',
  'STEALTH':'Stealth',
  'STEALTHDAMAGEMULTIPLIER':'Stealth Damage Multiplier',
  'DISTANCEDAMAGEMULTIPLIER':'Distance Damage Multiplier',
  'HEIGHTOFFSET':'HeightOffset',
  'SPAWNOBJECT':'SpawnObject',
  'SPAWNEFFECT':'SpawnEffect',
  'SPAWNFXOVERRIDESIMPACTFX':'SpawnFXOverridesImpactFX',
  'SPAWNLIFETIME':'SpawnLifetime',
  'AICALCULATIONSKILLOVERRIDE':'AiCalculationSkillOverride',
  'ADDWEAPONRANGE':'AddWeaponRange',
  'ISMELEE':'IsMelee',
  'AOECONDITIONS':'AoEConditions',
  'FXSCALE':'FXScale',
  'CASTSELFANIMATION':'CastSelfAnimation',
  'WEAPONBONES':'WeaponBones',
  'TARGETEFFECT':'TargetEffect',
  'TARGETGROUNDEFFECT':'TargetGroundEffect',
  'POSITIONEFFECT':'PositionEffect',
  'BEAMEFFECT':'BeamEffect',
  'SKILLEFFECT':'SkillEffect',
  'CLEANSESTATUSES':'CleanseStatuses',
  'STATUSCLEARCHANCE':'StatusClearChance',
  'AUTOCAST':'Autocast',
  'RANGE':'Range',
  'SURFACETYPE':'SurfaceType',
  'IGNORECURSED':'IgnoreCursed',
  'SURFACELIFETIME':'SurfaceLifetime',
  'SURFACESTATUSCHANCE':'SurfaceStatusChance',
  'SURFACEGROWSTEP':'SurfaceGrowStep',
  'SURFACEGROWINTERVAL':'SurfaceGrowInterval',
  'CASTEFFECTTEXTEVENT':'CastEffectTextEvent',
  'PUSHDISTANCE':'PushDistance',
  'BACKSTART':'BackStart',
  'FRONTOFFSET':'FrontOffset',
  'LIFETIME':'Lifetime',
  'AURASELF':'AuraSelf',
  'AURAALLIES':'AuraAllies',
  'AURANEUTRALS':'AuraNeutrals',
  'AURAENEMIES':'AuraEnemies',
  'AURAITEMS':'AuraItems',
  'DOMEEFFECT':'DomeEffect',
  'HITRADIUS':'HitRadius',
  'DAMAGEONJUMP':'Damage On Jump',
  'DAMAGEONLANDING':'Damage On Landing',
  'TELEPORTTEXTEVENT':'TeleportTextEvent',
  'LANDINGEFFECT':'LandingEffect',
  'MAXATTACKS':'MaxAttacks',
  'NEXTATTACKCHANCE':'NextAttackChance',
  'NEXTATTACKCHANCEDIVIDER':'NextAttackChanceDivider',
  'ENDPOSRADIUS':'EndPosRadius',
  'JUMPDELAY':'JumpDelay',
  'PREPAREEFFECTBONE':'PrepareEffectBone',
  'MALEIMPACTEFFECTS':'MaleImpactEffects',
  'FEMALEIMPACTEFFECTS':'FemaleImpactEffects',
  'REAPPEAREFFECT':'ReappearEffect',
  'REAPPEAREFFECTTEXTEVENT':'ReappearEffectTextEvent',
  'SURFACERADIUS':'SurfaceRadius',
  'MAXDISTANCE':'MaxDistance',
  'OFFSET':'Offset',
  'HEIGHT':'Height',
  'TRAVELSPEED':'TravelSpeed',
  'FLYEFFECT':'FlyEffect',
  'IMPACTEFFECT':'ImpactEffect',
  'SKILLBOOK':'Skillbook',
  'STRIKECOUNT':'StrikeCount',
  'STRIKEDELAY':'StrikeDelay',
  'OVERRIDESKILLLEVEL':'OverrideSkillLevel',
  'TARGETPROJECTILES':'TargetProjectiles',
  'SINGLESOURCE':'SingleSource',
  'DISTRIBUTION':'Distribution',
  'SHUFFLE':'Shuffle',
  'PREVIEWSTRIKEHITS':'PreviewStrikeHits',
  'TOTALSURFACECELLS':'TotalSurfaceCells',
  'SURFACEMINSPAWNRADIUS':'SurfaceMinSpawnRadius',
  'SHOCKWAVEDURATION':'ShockWaveDuration',
  'MINSURFACES':'MinSurfaces',
  'MAXSURFACES':'MaxSurfaces',
  'RAINEFFECT':'RainEffect',
  'ATMOSPHERE':'Atmosphere',
  'CONSEQUENCESSTARTTIME':'ConsequencesStartTime',
  'CONSEQUENCESDURATION':'ConsequencesDuration',
  'CONTINUEONKILL':'ContinueOnKill',
  'CONTINUEEFFECT':'ContinueEffect',
  'TARGETCASTEFFECT':'TargetCastEffect',
  'TARGETHITEFFECT':'TargetHitEffect',
  'STARTTEXTEVENT':'StartTextEvent',
  'STOPTEXTEVENT':'StopTextEvent',
  'HITEFFECT':'HitEffect',
  'PUSHPULLEFFECT':'PushPullEffect',
  'MINHITSPERTURN':'MinHitsPerTurn',
  'MAXHITSPERTURN':'MaxHitsPerTurn',
  'HITDELAY':'HitDelay',
  'STORMEFFECT':'StormEffect',
  'PROJECTILESKILLS':'ProjectileSkills',
  'SUMMONLEVEL':'SummonLevel',
  'TEMPLATEADVANCED':'TemplateAdvanced',
  'TEMPLATEOVERRIDE':'TemplateOverride',
  'TOTEM':'Totem',
  'LINKTELEPORTS':'LinkTeleports',
  'SUMMONCOUNT':'SummonCount',
  'ACCELERATION':'Acceleration',
  'TELEPORTDELAY':'TeleportDelay',
  'TELEPORTSELF':'TeleportSelf',
  'TELEPORTSURFACE':'TeleportSurface',
  'SELECTEDCHARACTEREFFECT':'SelectedCharacterEffect',
  'SELECTEDOBJECTEFFECT':'SelectedObjectEffect',
  'SELECTEDPOSITIONEFFECT':'SelectedPositionEffect',
  'DISAPPEAREFFECT':'DisappearEffect',
  'FORCEMOVE':'ForceMove',
  'RANDOMPOINTS':'RandomPoints',
  'POINTSMAXOFFSET':'PointsMaxOffset',
  'GROWSPEED':'GrowSpeed',
  'GROWTIMEOUT':'GrowTimeout',
  'SOURCETARGETEFFECT':'SourceTargetEffect',
  'TARGETTARGETEFFECT':'TargetTargetEffect',
  'TEMPLATE1':'Template1',
  'TEMPLATE2':'Template2',
  'TEMPLATE3':'Template3',
  'SHAPE':'Shape',
  'BASE':'Base'
};

const PROJECTILE_NAMES = {
  'NAME':'Name',
  'USING':'Using',
  'SKILLTYPE':'SkillType',
  'LEVEL':'Level',
  'FORGAMEMASTER':'ForGameMaster',
  'ISENEMYSKILL':'IsEnemySkill',
  'ABILITY':'Ability',
  'TIER':'Tier',
  'REQUIREMENT':'Requirement',
  'ACTIONPOINTS':'ActionPoints',
  'COOLDOWN':'Cooldown',
  'AIFLAGS':'AIFlags',
  'DAMAGE':'Damage',
  'DAMAGEMULTIPLIER':'Damage Multiplier',
  'DAMAGERANGE':'Damage Range',
  'DAMAGETYPE':'DamageType',
  'SKILLPROPERTIES':'SkillProperties',
  'TARGETRADIUS':'TargetRadius',
  'ADDRANGEFROMABILITY':'AddRangeFromAbility',
  'AREARADIUS':'AreaRadius',
  'DEATHTYPE':'DeathType',
  'EXPLODERADIUS':'ExplodeRadius',
  'CANTARGETCHARACTERS':'CanTargetCharacters',
  'CANTARGETITEMS':'CanTargetItems',
  'CANTARGETTERRAIN':'CanTargetTerrain',
  'FORCETARGET':'ForceTarget',
  'AMOUNTOFTARGETS':'AmountOfTargets',
  'AUTOAIM':'AutoAim',
  'TARGETCONDITIONS':'TargetConditions',
  'FORKINGCONDITIONS':'ForkingConditions',
  'USECHARACTERSTATS':'UseCharacterStats',
  'USEWEAPONDAMAGE':'UseWeaponDamage',
  'USEWEAPONPROPERTIES':'UseWeaponProperties',
  'PROJECTILECOUNT':'ProjectileCount',
  'PROJECTILEDELAY':'ProjectileDelay',
  'ANGLE':'Angle',
  'TEMPLATE':'Template',
  'IGNOREVISIONBLOCK':'IgnoreVisionBlock',
  'TEMPLATECHECK':'TemplateCheck',
  'CHANCETOPIERCE':'ChanceToPierce',
  'MAXPIERCECOUNT':'MaxPierceCount',
  'MAXFORKCOUNT':'MaxForkCount',
  'FORKLEVELS':'ForkLevels',
  'FORKCHANCE':'ForkChance',
  'ICON':'Icon',
  'DISPLAYNAME':'DisplayName',
  'DESCRIPTION':'Description',
  'STATSDESCRIPTION':'StatsDescription',
  'STATSDESCRIPTIONPARAMS':'StatsDescriptionParams',
  'PREPAREANIMATIONINIT':'PrepareAnimationInit',
  'PREPAREANIMATIONLOOP':'PrepareAnimationLoop',
  'PREPAREEFFECT':'PrepareEffect',
  'CASTANIMATION':'CastAnimation',
  'CASTANIMATIONCHECK':'CastAnimationCheck',
  'CASTTEXTEVENT':'CastTextEvent',
  'CASTEFFECT':'CastEffect',
  'PREVIEWEFFECT':'PreviewEffect',
  'REQUIREMENTS':'Requirements',
  'MEMORIZATIONREQUIREMENTS':'MemorizationRequirements',
  'MEMORYCOST':'Memory Cost',
  'MAGICCOST':'Magic Cost',
  'DIVIDEDAMAGE':'DivideDamage',
  'PROJECTILETERRAINOFFSET':'ProjectileTerrainOffset',
  'MOVINGOBJECT':'MovingObject',
  'PROJECTILETYPE':'ProjectileType',
  'OVERRIDEMINAP':'OverrideMinAP',
  'STEALTH':'Stealth',
  'STEALTHDAMAGEMULTIPLIER':'Stealth Damage Multiplier',
  'DISTANCEDAMAGEMULTIPLIER':'Distance Damage Multiplier',
  'HEIGHTOFFSET':'HeightOffset',
  'SPAWNOBJECT':'SpawnObject',
  'SPAWNEFFECT':'SpawnEffect',
  'SPAWNFXOVERRIDESIMPACTFX':'SpawnFXOverridesImpactFX',
  'SPAWNLIFETIME':'SpawnLifetime',
  'AICALCULATIONSKILLOVERRIDE':'AiCalculationSkillOverride'
};

const TARGET_NAMES = {
  'NAME':'Name',
  'USING':'Using',
  'SKILLTYPE':'SkillType',
  'LEVEL':'Level',
  'FORGAMEMASTER':'ForGameMaster',
  'ISENEMYSKILL':'IsEnemySkill',
  'ABILITY':'Ability',
  'TIER':'Tier',
  'REQUIREMENT':'Requirement',
  'ACTIONPOINTS':'ActionPoints',
  'COOLDOWN':'Cooldown',
  'AIFLAGS':'AIFlags',
  'DAMAGE':'Damage',
  'DAMAGEMULTIPLIER':'Damage Multiplier',
  'DAMAGERANGE':'Damage Range',
  'DAMAGETYPE':'DamageType',
  'SKILLPROPERTIES':'SkillProperties',
  'TARGETRADIUS':'TargetRadius',
  'AREARADIUS':'AreaRadius',
  'ADDWEAPONRANGE':'AddWeaponRange',
  'ISMELEE':'IsMelee',
  'DEATHTYPE':'DeathType',
  'REQUIREMENTS':'Requirements',
  'MEMORIZATIONREQUIREMENTS':'MemorizationRequirements',
  'CANTARGETCHARACTERS':'CanTargetCharacters',
  'CANTARGETITEMS':'CanTargetItems',
  'CANTARGETTERRAIN':'CanTargetTerrain',
  'MEMORYCOST':'Memory Cost',
  'MAGICCOST':'Magic Cost',
  'TARGETCONDITIONS':'TargetConditions',
  'AOECONDITIONS':'AoEConditions',
  'USECHARACTERSTATS':'UseCharacterStats',
  'USEWEAPONDAMAGE':'UseWeaponDamage',
  'USEWEAPONPROPERTIES':'UseWeaponProperties',
  'ICON':'Icon',
  'DISPLAYNAME':'DisplayName',
  'DESCRIPTION':'Description',
  'STATSDESCRIPTION':'StatsDescription',
  'STATSDESCRIPTIONPARAMS':'StatsDescriptionParams',
  'FXSCALE':'FXScale',
  'PREPAREANIMATIONINIT':'PrepareAnimationInit',
  'PREPAREANIMATIONLOOP':'PrepareAnimationLoop',
  'PREPAREEFFECT':'PrepareEffect',
  'CASTANIMATION':'CastAnimation',
  'CASTSELFANIMATION':'CastSelfAnimation',
  'CASTTEXTEVENT':'CastTextEvent',
  'CASTEFFECT':'CastEffect',
  'PREVIEWEFFECT':'PreviewEffect',
  'WEAPONBONES':'WeaponBones',
  'TARGETEFFECT':'TargetEffect',
  'TARGETGROUNDEFFECT':'TargetGroundEffect',
  'POSITIONEFFECT':'PositionEffect',
  'BEAMEFFECT':'BeamEffect',
  'SKILLEFFECT':'SkillEffect',
  'CLEANSESTATUSES':'CleanseStatuses',
  'STATUSCLEARCHANCE':'StatusClearChance',
  'AUTOCAST':'Autocast',
  'IGNOREVISIONBLOCK':'IgnoreVisionBlock',
  'STEALTH':'Stealth',
  'STEALTHDAMAGEMULTIPLIER':'Stealth Damage Multiplier',
  'OVERRIDEMINAP':'OverrideMinAP',
  'AMOUNTOFTARGETS':'AmountOfTargets',
  'AICALCULATIONSKILLOVERRIDE':'AiCalculationSkillOverride'
};

const CONE_NAMES = {
  'NAME':'Name',
  'USING':'Using',
  'SKILLTYPE':'SkillType',
  'LEVEL':'Level',
  'FORGAMEMASTER':'ForGameMaster',
  'ISENEMYSKILL':'IsEnemySkill',
  'ABILITY':'Ability',
  'TIER':'Tier',
  'REQUIREMENT':'Requirement',
  'ACTIONPOINTS':'ActionPoints',
  'COOLDOWN':'Cooldown',
  'AIFLAGS':'AIFlags',
  'DAMAGE':'Damage',
  'DAMAGEMULTIPLIER':'Damage Multiplier',
  'DAMAGERANGE':'Damage Range',
  'DAMAGETYPE':'DamageType',
  'SKILLPROPERTIES':'SkillProperties',
  'RANGE':'Range',
  'ANGLE':'Angle',
  'DEATHTYPE':'DeathType',
  'SURFACETYPE':'SurfaceType',
  'IGNORECURSED':'IgnoreCursed',
  'SURFACELIFETIME':'SurfaceLifetime',
  'SURFACESTATUSCHANCE':'SurfaceStatusChance',
  'SURFACEGROWSTEP':'SurfaceGrowStep',
  'SURFACEGROWINTERVAL':'SurfaceGrowInterval',
  'TARGETCONDITIONS':'TargetConditions',
  'USEWEAPONDAMAGE':'UseWeaponDamage',
  'USEWEAPONPROPERTIES':'UseWeaponProperties',
  'CANTARGETCHARACTERS':'CanTargetCharacters',
  'CANTARGETITEMS':'CanTargetItems',
  'ICON':'Icon',
  'DISPLAYNAME':'DisplayName',
  'DESCRIPTION':'Description',
  'STATSDESCRIPTION':'StatsDescription',
  'STATSDESCRIPTIONPARAMS':'StatsDescriptionParams',
  'FXSCALE':'FXScale',
  'PREPAREANIMATIONINIT':'PrepareAnimationInit',
  'PREPAREANIMATIONLOOP':'PrepareAnimationLoop',
  'PREPAREEFFECT':'PrepareEffect',
  'CASTANIMATION':'CastAnimation',
  'CASTTEXTEVENT':'CastTextEvent',
  'CASTEFFECT':'CastEffect',
  'CASTEFFECTTEXTEVENT':'CastEffectTextEvent',
  'MEMORYCOST':'Memory Cost',
  'MAGICCOST':'Magic Cost',
  'REQUIREMENTS':'Requirements',
  'MEMORIZATIONREQUIREMENTS':'MemorizationRequirements',
  'PUSHDISTANCE':'PushDistance',
  'STEALTH':'Stealth',
  'BACKSTART':'BackStart',
  'FRONTOFFSET':'FrontOffset',
  'OVERRIDEMINAP':'OverrideMinAP'
};

const DOME_NAMES = {
  'NAME':'Name',
  'USING':'Using',
  'SKILLTYPE':'SkillType',
  'LEVEL':'Level',
  'FORGAMEMASTER':'ForGameMaster',
  'ISENEMYSKILL':'IsEnemySkill',
  'ABILITY':'Ability',
  'TIER':'Tier',
  'REQUIREMENT':'Requirement',
  'ACTIONPOINTS':'ActionPoints',
  'COOLDOWN':'Cooldown',
  'AIFLAGS':'AIFlags',
  'LIFETIME':'Lifetime',
  'SKILLPROPERTIES':'SkillProperties',
  'TARGETCONDITIONS':'TargetConditions',
  'AURASELF':'AuraSelf',
  'AURAALLIES':'AuraAllies',
  'AURANEUTRALS':'AuraNeutrals',
  'AURAENEMIES':'AuraEnemies',
  'AURAITEMS':'AuraItems',
  'TARGETRADIUS':'TargetRadius',
  'USECHARACTERSTATS':'UseCharacterStats',
  'AREARADIUS':'AreaRadius',
  'REQUIREMENTS':'Requirements',
  'MEMORIZATIONREQUIREMENTS':'MemorizationRequirements',
  'ICON':'Icon',
  'DISPLAYNAME':'DisplayName',
  'DESCRIPTION':'Description',
  'STATSDESCRIPTION':'StatsDescription',
  'STATSDESCRIPTIONPARAMS':'StatsDescriptionParams',
  'FXSCALE':'FXScale',
  'PREPAREANIMATIONINIT':'PrepareAnimationInit',
  'PREPAREANIMATIONLOOP':'PrepareAnimationLoop',
  'PREPAREEFFECT':'PrepareEffect',
  'CASTANIMATION':'CastAnimation',
  'CASTTEXTEVENT':'CastTextEvent',
  'CASTEFFECT':'CastEffect',
  'CASTEFFECTTEXTEVENT':'CastEffectTextEvent',
  'TARGETEFFECT':'TargetEffect',
  'MEMORYCOST':'Memory Cost',
  'MAGICCOST':'Magic Cost',
  'DOMEEFFECT':'DomeEffect',
  'STEALTH':'Stealth'
};

const JUMP_NAMES = {
  'NAME':'Name',
  'USING':'Using',
  'SKILLTYPE':'SkillType',
  'LEVEL':'Level',
  'FORGAMEMASTER':'ForGameMaster',
  'ISENEMYSKILL':'IsEnemySkill',
  'ABILITY':'Ability',
  'TIER':'Tier',
  'REQUIREMENT':'Requirement',
  'ACTIONPOINTS':'ActionPoints',
  'COOLDOWN':'Cooldown',
  'AIFLAGS':'AIFlags',
  'DAMAGE':'Damage',
  'DAMAGEMULTIPLIER':'Damage Multiplier',
  'DAMAGERANGE':'Damage Range',
  'DAMAGETYPE':'DamageType',
  'SKILLPROPERTIES':'SkillProperties',
  'TARGETRADIUS':'TargetRadius',
  'HITRADIUS':'HitRadius',
  'DEATHTYPE':'DeathType',
  'DAMAGEONJUMP':'Damage On Jump',
  'DAMAGEONLANDING':'Damage On Landing',
  'ICON':'Icon',
  'DISPLAYNAME':'DisplayName',
  'DESCRIPTION':'Description',
  'STATSDESCRIPTION':'StatsDescription',
  'STATSDESCRIPTIONPARAMS':'StatsDescriptionParams',
  'FXSCALE':'FXScale',
  'PREPAREANIMATIONINIT':'PrepareAnimationInit',
  'PREPAREANIMATIONLOOP':'PrepareAnimationLoop',
  'PREPAREEFFECT':'PrepareEffect',
  'CASTANIMATION':'CastAnimation',
  'CASTTEXTEVENT':'CastTextEvent',
  'TELEPORTTEXTEVENT':'TeleportTextEvent',
  'CASTEFFECT':'CastEffect',
  'PREVIEWEFFECT':'PreviewEffect',
  'LANDINGEFFECT':'LandingEffect',
  'MEMORYCOST':'Memory Cost',
  'MAGICCOST':'Magic Cost',
  'REQUIREMENTS':'Requirements',
  'MEMORIZATIONREQUIREMENTS':'MemorizationRequirements',
  'STEALTH':'Stealth'
};

const MULTISTRIKE_NAMES = {
  'NAME':'Name',
  'USING':'Using',
  'SKILLTYPE':'SkillType',
  'LEVEL':'Level',
  'FORGAMEMASTER':'ForGameMaster',
  'ISENEMYSKILL':'IsEnemySkill',
  'ABILITY':'Ability',
  'TIER':'Tier',
  'REQUIREMENT':'Requirement',
  'ACTIONPOINTS':'ActionPoints',
  'COOLDOWN':'Cooldown',
  'AIFLAGS':'AIFlags',
  'DAMAGE':'Damage',
  'DAMAGEMULTIPLIER':'Damage Multiplier',
  'DAMAGERANGE':'Damage Range',
  'DAMAGETYPE':'DamageType',
  'SKILLPROPERTIES':'SkillProperties',
  'TARGETRADIUS':'TargetRadius',
  'AREARADIUS':'AreaRadius',
  'DEATHTYPE':'DeathType',
  'MAXATTACKS':'MaxAttacks',
  'NEXTATTACKCHANCE':'NextAttackChance',
  'NEXTATTACKCHANCEDIVIDER':'NextAttackChanceDivider',
  'ENDPOSRADIUS':'EndPosRadius',
  'JUMPDELAY':'JumpDelay',
  'REQUIREMENTS':'Requirements',
  'MEMORIZATIONREQUIREMENTS':'MemorizationRequirements',
  'TARGETCONDITIONS':'TargetConditions',
  'USEWEAPONDAMAGE':'UseWeaponDamage',
  'USEWEAPONPROPERTIES':'UseWeaponProperties',
  'ICON':'Icon',
  'DISPLAYNAME':'DisplayName',
  'DESCRIPTION':'Description',
  'STATSDESCRIPTION':'StatsDescription',
  'STATSDESCRIPTIONPARAMS':'StatsDescriptionParams',
  'FXSCALE':'FXScale',
  'PREPAREANIMATIONINIT':'PrepareAnimationInit',
  'PREPAREANIMATIONLOOP':'PrepareAnimationLoop',
  'PREPAREEFFECT':'PrepareEffect',
  'PREPAREEFFECTBONE':'PrepareEffectBone',
  'CASTANIMATION':'CastAnimation',
  'CASTTEXTEVENT':'CastTextEvent',
  'CASTEFFECT':'CastEffect',
  'CASTEFFECTTEXTEVENT':'CastEffectTextEvent',
  'MALEIMPACTEFFECTS':'MaleImpactEffects',
  'FEMALEIMPACTEFFECTS':'FemaleImpactEffects',
  'REAPPEAREFFECT':'ReappearEffect',
  'REAPPEAREFFECTTEXTEVENT':'ReappearEffectTextEvent',
  'MEMORYCOST':'Memory Cost',
  'MAGICCOST':'Magic Cost',
  'STEALTH':'Stealth',
  'OVERRIDEMINAP':'OverrideMinAP'
};

const PATH_NAMES = {
  'NAME':'Name',
  'USING':'Using',
  'SKILLTYPE':'SkillType',
  'LEVEL':'Level',
  'FORGAMEMASTER':'ForGameMaster',
  'ISENEMYSKILL':'IsEnemySkill',
  'ABILITY':'Ability',
  'TIER':'Tier',
  'REQUIREMENT':'Requirement',
  'ACTIONPOINTS':'ActionPoints',
  'COOLDOWN':'Cooldown',
  'AIFLAGS':'AIFlags',
  'SURFACETYPE':'SurfaceType',
  'SURFACERADIUS':'SurfaceRadius',
  'SURFACELIFETIME':'SurfaceLifetime',
  'SURFACESTATUSCHANCE':'SurfaceStatusChance',
  'SKILLPROPERTIES':'SkillProperties',
  'MAXDISTANCE':'MaxDistance',
  'OFFSET':'Offset',
  'HITRADIUS':'HitRadius',
  'HEIGHT':'Height',
  'TRAVELSPEED':'TravelSpeed',
  'REQUIREMENTS':'Requirements',
  'MEMORIZATIONREQUIREMENTS':'MemorizationRequirements',
  'ICON':'Icon',
  'DISPLAYNAME':'DisplayName',
  'DESCRIPTION':'Description',
  'STATSDESCRIPTION':'StatsDescription',
  'STATSDESCRIPTIONPARAMS':'StatsDescriptionParams',
  'FXSCALE':'FXScale',
  'PREPAREANIMATIONINIT':'PrepareAnimationInit',
  'PREPAREANIMATIONLOOP':'PrepareAnimationLoop',
  'PREPAREEFFECT':'PrepareEffect',
  'CASTANIMATION':'CastAnimation',
  'CASTTEXTEVENT':'CastTextEvent',
  'CASTEFFECT':'CastEffect',
  'CASTEFFECTTEXTEVENT':'CastEffectTextEvent',
  'TARGETEFFECT':'TargetEffect',
  'FLYEFFECT':'FlyEffect',
  'IMPACTEFFECT':'ImpactEffect',
  'MEMORYCOST':'Memory Cost',
  'MAGICCOST':'Magic Cost',
  'SKILLBOOK':'Skillbook',
  'STEALTH':'Stealth'
};

const PROJECTILESTRIKE_NAMES = {
  'NAME':'Name',
  'USING':'Using',
  'SKILLTYPE':'SkillType',
  'LEVEL':'Level',
  'FORGAMEMASTER':'ForGameMaster',
  'ISENEMYSKILL':'IsEnemySkill',
  'ABILITY':'Ability',
  'TIER':'Tier',
  'REQUIREMENT':'Requirement',
  'ACTIONPOINTS':'ActionPoints',
  'COOLDOWN':'Cooldown',
  'AIFLAGS':'AIFlags',
  'DAMAGE':'Damage',
  'DAMAGEMULTIPLIER':'Damage Multiplier',
  'DAMAGERANGE':'Damage Range',
  'DAMAGETYPE':'DamageType',
  'SKILLPROPERTIES':'SkillProperties',
  'TARGETRADIUS':'TargetRadius',
  'ADDRANGEFROMABILITY':'AddRangeFromAbility',
  'AREARADIUS':'AreaRadius',
  'DEATHTYPE':'DeathType',
  'EXPLODERADIUS':'ExplodeRadius',
  'STRIKECOUNT':'StrikeCount',
  'STRIKEDELAY':'StrikeDelay',
  'CANTARGETCHARACTERS':'CanTargetCharacters',
  'CANTARGETITEMS':'CanTargetItems',
  'CANTARGETTERRAIN':'CanTargetTerrain',
  'FORCETARGET':'ForceTarget',
  'TARGETCONDITIONS':'TargetConditions',
  'OVERRIDESKILLLEVEL':'OverrideSkillLevel',
  'USECHARACTERSTATS':'UseCharacterStats',
  'USEWEAPONDAMAGE':'UseWeaponDamage',
  'USEWEAPONPROPERTIES':'UseWeaponProperties',
  'TARGETPROJECTILES':'TargetProjectiles',
  'PROJECTILECOUNT':'ProjectileCount',
  'PROJECTILEDELAY':'ProjectileDelay',
  'ANGLE':'Angle',
  'HEIGHT':'Height',
  'SINGLESOURCE':'SingleSource',
  'TEMPLATE':'Template',
  'MAXFORKCOUNT':'MaxForkCount',
  'FORKLEVELS':'ForkLevels',
  'FORKCHANCE':'ForkChance',
  'ICON':'Icon',
  'DISPLAYNAME':'DisplayName',
  'DESCRIPTION':'Description',
  'STATSDESCRIPTION':'StatsDescription',
  'STATSDESCRIPTIONPARAMS':'StatsDescriptionParams',
  'PREPAREANIMATIONINIT':'PrepareAnimationInit',
  'PREPAREANIMATIONLOOP':'PrepareAnimationLoop',
  'PREPAREEFFECT':'PrepareEffect',
  'CASTANIMATION':'CastAnimation',
  'CASTTEXTEVENT':'CastTextEvent',
  'CASTEFFECT':'CastEffect',
  'PREVIEWEFFECT':'PreviewEffect',
  'REQUIREMENTS':'Requirements',
  'MEMORIZATIONREQUIREMENTS':'MemorizationRequirements',
  'MEMORYCOST':'Memory Cost',
  'MAGICCOST':'Magic Cost',
  'PROJECTILETYPE':'ProjectileType',
  'STEALTH':'Stealth',
  'DISTRIBUTION':'Distribution',
  'SHUFFLE':'Shuffle',
  'PREVIEWSTRIKEHITS':'PreviewStrikeHits'
};

const QUAKE_NAMES = {
  'NAME':'Name',
  'USING':'Using',
  'SKILLTYPE':'SkillType',
  'LEVEL':'Level',
  'FORGAMEMASTER':'ForGameMaster',
  'ISENEMYSKILL':'IsEnemySkill',
  'ABILITY':'Ability',
  'TIER':'Tier',
  'REQUIREMENT':'Requirement',
  'ACTIONPOINTS':'ActionPoints',
  'COOLDOWN':'Cooldown',
  'AIFLAGS':'AIFlags',
  'DAMAGE':'Damage',
  'DAMAGEMULTIPLIER':'Damage Multiplier',
  'DAMAGERANGE':'Damage Range',
  'DAMAGETYPE':'DamageType',
  'SKILLPROPERTIES':'SkillProperties',
  'TOTALSURFACECELLS':'TotalSurfaceCells',
  'AREARADIUS':'AreaRadius',
  'TARGETCONDITIONS':'TargetConditions',
  'OVERRIDESKILLLEVEL':'OverrideSkillLevel',
  'SURFACEMINSPAWNRADIUS':'SurfaceMinSpawnRadius',
  'DEATHTYPE':'DeathType',
  'SHOCKWAVEDURATION':'ShockWaveDuration',
  'MINSURFACES':'MinSurfaces',
  'MAXSURFACES':'MaxSurfaces',
  'SURFACETYPE':'SurfaceType',
  'SURFACEGROWSTEP':'SurfaceGrowStep',
  'SURFACEGROWINTERVAL':'SurfaceGrowInterval',
  'SURFACELIFETIME':'SurfaceLifetime',
  'SURFACESTATUSCHANCE':'SurfaceStatusChance',
  'ICON':'Icon',
  'DISPLAYNAME':'DisplayName',
  'DESCRIPTION':'Description',
  'STATSDESCRIPTION':'StatsDescription',
  'STATSDESCRIPTIONPARAMS':'StatsDescriptionParams',
  'FXSCALE':'FXScale',
  'PREPAREANIMATIONINIT':'PrepareAnimationInit',
  'PREPAREANIMATIONLOOP':'PrepareAnimationLoop',
  'PREPAREEFFECT':'PrepareEffect',
  'CASTANIMATION':'CastAnimation',
  'CASTTEXTEVENT':'CastTextEvent',
  'CASTEFFECT':'CastEffect',
  'CASTEFFECTTEXTEVENT':'CastEffectTextEvent',
  'LANDINGEFFECT':'LandingEffect',
  'MEMORYCOST':'Memory Cost',
  'MAGICCOST':'Magic Cost',
  'REQUIREMENTS':'Requirements',
  'MEMORIZATIONREQUIREMENTS':'MemorizationRequirements',
  'SKILLBOOK':'Skillbook',
  'STEALTH':'Stealth'
};

const RAIN_NAMES = {
  'NAME':'Name',
  'USING':'Using',
  'SKILLTYPE':'SkillType',
  'LEVEL':'Level',
  'FORGAMEMASTER':'ForGameMaster',
  'ISENEMYSKILL':'IsEnemySkill',
  'ABILITY':'Ability',
  'TIER':'Tier',
  'REQUIREMENT':'Requirement',
  'ACTIONPOINTS':'ActionPoints',
  'COOLDOWN':'Cooldown',
  'AIFLAGS':'AIFlags',
  'LIFETIME':'Lifetime',
  'SURFACETYPE':'SurfaceType',
  'SURFACELIFETIME':'SurfaceLifetime',
  'SURFACESTATUSCHANCE':'SurfaceStatusChance',
  'DAMAGE':'Damage',
  'DAMAGEMULTIPLIER':'Damage Multiplier',
  'DAMAGERANGE':'Damage Range',
  'DAMAGETYPE':'DamageType',
  'DEATHTYPE':'DeathType',
  'SKILLPROPERTIES':'SkillProperties',
  'TARGETRADIUS':'TargetRadius',
  'TARGETCONDITIONS':'TargetConditions',
  'USECHARACTERSTATS':'UseCharacterStats',
  'USEWEAPONDAMAGE':'UseWeaponDamage',
  'USEWEAPONPROPERTIES':'UseWeaponProperties',
  'AREARADIUS':'AreaRadius',
  'TOTALSURFACECELLS':'TotalSurfaceCells',
  'SURFACEGROWSTEP':'SurfaceGrowStep',
  'SURFACEGROWINTERVAL':'SurfaceGrowInterval',
  'REQUIREMENTS':'Requirements',
  'MEMORIZATIONREQUIREMENTS':'MemorizationRequirements',
  'ICON':'Icon',
  'DISPLAYNAME':'DisplayName',
  'DESCRIPTION':'Description',
  'STATSDESCRIPTION':'StatsDescription',
  'STATSDESCRIPTIONPARAMS':'StatsDescriptionParams',
  'FXSCALE':'FXScale',
  'PREPAREANIMATIONINIT':'PrepareAnimationInit',
  'PREPAREANIMATIONLOOP':'PrepareAnimationLoop',
  'PREPAREEFFECT':'PrepareEffect',
  'CASTANIMATION':'CastAnimation',
  'CASTTEXTEVENT':'CastTextEvent',
  'CASTEFFECT':'CastEffect',
  'CASTEFFECTTEXTEVENT':'CastEffectTextEvent',
  'TARGETEFFECT':'TargetEffect',
  'MEMORYCOST':'Memory Cost',
  'MAGICCOST':'Magic Cost',
  'RAINEFFECT':'RainEffect',
  'ATMOSPHERE':'Atmosphere',
  'CONSEQUENCESSTARTTIME':'ConsequencesStartTime',
  'CONSEQUENCESDURATION':'ConsequencesDuration',
  'STEALTH':'Stealth'
};

const RUSH_NAMES = {
  'NAME':'Name',
  'USING':'Using',
  'SKILLTYPE':'SkillType',
  'LEVEL':'Level',
  'FORGAMEMASTER':'ForGameMaster',
  'ISENEMYSKILL':'IsEnemySkill',
  'ABILITY':'Ability',
  'TIER':'Tier',
  'REQUIREMENT':'Requirement',
  'ACTIONPOINTS':'ActionPoints',
  'COOLDOWN':'Cooldown',
  'AIFLAGS':'AIFlags',
  'DAMAGE':'Damage',
  'DAMAGEMULTIPLIER':'Damage Multiplier',
  'DAMAGERANGE':'Damage Range',
  'DAMAGETYPE':'DamageType',
  'SKILLPROPERTIES':'SkillProperties',
  'DEATHTYPE':'DeathType',
  'TARGETRADIUS':'TargetRadius',
  'HITRADIUS':'HitRadius',
  'CANTARGETCHARACTERS':'CanTargetCharacters',
  'CANTARGETITEMS':'CanTargetItems',
  'CANTARGETTERRAIN':'CanTargetTerrain',
  'TARGETCONDITIONS':'TargetConditions',
  'USECHARACTERSTATS':'UseCharacterStats',
  'USEWEAPONDAMAGE':'UseWeaponDamage',
  'USEWEAPONPROPERTIES':'UseWeaponProperties',
  'CONTINUEONKILL':'ContinueOnKill',
  'CONTINUEEFFECT':'ContinueEffect',
  'ICON':'Icon',
  'DISPLAYNAME':'DisplayName',
  'DESCRIPTION':'Description',
  'STATSDESCRIPTION':'StatsDescription',
  'STATSDESCRIPTIONPARAMS':'StatsDescriptionParams',
  'FXSCALE':'FXScale',
  'PREPAREANIMATIONINIT':'PrepareAnimationInit',
  'PREPAREANIMATIONLOOP':'PrepareAnimationLoop',
  'PREPAREEFFECT':'PrepareEffect',
  'CASTANIMATION':'CastAnimation',
  'CASTTEXTEVENT':'CastTextEvent',
  'CASTEFFECT':'CastEffect',
  'CASTEFFECTTEXTEVENT':'CastEffectTextEvent',
  'WEAPONBONES':'WeaponBones',
  'MEMORYCOST':'Memory Cost',
  'MAGICCOST':'Magic Cost',
  'TARGETEFFECT':'TargetEffect',
  'TARGETCASTEFFECT':'TargetCastEffect',
  'TARGETHITEFFECT':'TargetHitEffect',
  'STARTTEXTEVENT':'StartTextEvent',
  'STOPTEXTEVENT':'StopTextEvent',
  'REQUIREMENTS':'Requirements',
  'MEMORIZATIONREQUIREMENTS':'MemorizationRequirements',
  'STEALTH':'Stealth',
  'OVERRIDEMINAP':'OverrideMinAP'
};

const SHOUT_NAMES = {
  'NAME':'Name',
  'USING':'Using',
  'SKILLTYPE':'SkillType',
  'LEVEL':'Level',
  'FORGAMEMASTER':'ForGameMaster',
  'ISENEMYSKILL':'IsEnemySkill',
  'ABILITY':'Ability',
  'TIER':'Tier',
  'REQUIREMENT':'Requirement',
  'ACTIONPOINTS':'ActionPoints',
  'COOLDOWN':'Cooldown',
  'AIFLAGS':'AIFlags',
  'DAMAGE':'Damage',
  'DAMAGEMULTIPLIER':'Damage Multiplier',
  'DAMAGERANGE':'Damage Range',
  'DAMAGETYPE':'DamageType',
  'SKILLPROPERTIES':'SkillProperties',
  'AREARADIUS':'AreaRadius',
  'ADDWEAPONRANGE':'AddWeaponRange',
  'DEATHTYPE':'DeathType',
  'TARGETCONDITIONS':'TargetConditions',
  'AOECONDITIONS':'AoEConditions',
  'USECHARACTERSTATS':'UseCharacterStats',
  'USEWEAPONDAMAGE':'UseWeaponDamage',
  'USEWEAPONPROPERTIES':'UseWeaponProperties',
  'AUTOCAST':'Autocast',
  'REQUIREMENTS':'Requirements',
  'MEMORIZATIONREQUIREMENTS':'MemorizationRequirements',
  'ICON':'Icon',
  'DISPLAYNAME':'DisplayName',
  'DESCRIPTION':'Description',
  'STATSDESCRIPTION':'StatsDescription',
  'STATSDESCRIPTIONPARAMS':'StatsDescriptionParams',
  'FXSCALE':'FXScale',
  'PREPAREANIMATIONINIT':'PrepareAnimationInit',
  'PREPAREANIMATIONLOOP':'PrepareAnimationLoop',
  'PREPAREEFFECT':'PrepareEffect',
  'CASTANIMATION':'CastAnimation',
  'CASTTEXTEVENT':'CastTextEvent',
  'CASTEFFECT':'CastEffect',
  'HITEFFECT':'HitEffect',
  'CASTEFFECTTEXTEVENT':'CastEffectTextEvent',
  'WEAPONBONES':'WeaponBones',
  'MEMORYCOST':'Memory Cost',
  'MAGICCOST':'Magic Cost',
  'CLEANSESTATUSES':'CleanseStatuses',
  'STATUSCLEARCHANCE':'StatusClearChance',
  'STEALTH':'Stealth',
  'PUSHDISTANCE':'PushDistance',
  'CANTARGETCHARACTERS':'CanTargetCharacters',
  'CANTARGETITEMS':'CanTargetItems',
  'PUSHPULLEFFECT':'PushPullEffect',
  'IGNOREVISIONBLOCK':'IgnoreVisionBlock',
  'AICALCULATIONSKILLOVERRIDE':'AiCalculationSkillOverride'
};

const STORM_NAMES = {
  'NAME':'Name',
  'USING':'Using',
  'SKILLTYPE':'SkillType',
  'LEVEL':'Level',
  'FORGAMEMASTER':'ForGameMaster',
  'ISENEMYSKILL':'IsEnemySkill',
  'ABILITY':'Ability',
  'TIER':'Tier',
  'REQUIREMENT':'Requirement',
  'ACTIONPOINTS':'ActionPoints',
  'COOLDOWN':'Cooldown',
  'AIFLAGS':'AIFlags',
  'DAMAGE':'Damage',
  'DAMAGEMULTIPLIER':'Damage Multiplier',
  'DAMAGERANGE':'Damage Range',
  'DAMAGETYPE':'DamageType',
  'SKILLPROPERTIES':'SkillProperties',
  'TARGETRADIUS':'TargetRadius',
  'AREARADIUS':'AreaRadius',
  'TARGETCONDITIONS':'TargetConditions',
  'OVERRIDESKILLLEVEL':'OverrideSkillLevel',
  'DEATHTYPE':'DeathType',
  'HITRADIUS':'HitRadius',
  'LIFETIME':'Lifetime',
  'MINHITSPERTURN':'MinHitsPerTurn',
  'MAXHITSPERTURN':'MaxHitsPerTurn',
  'HITDELAY':'HitDelay',
  'REQUIREMENTS':'Requirements',
  'MEMORIZATIONREQUIREMENTS':'MemorizationRequirements',
  'ICON':'Icon',
  'DISPLAYNAME':'DisplayName',
  'DESCRIPTION':'Description',
  'STATSDESCRIPTION':'StatsDescription',
  'STATSDESCRIPTIONPARAMS':'StatsDescriptionParams',
  'FXSCALE':'FXScale',
  'PREPAREANIMATIONINIT':'PrepareAnimationInit',
  'PREPAREANIMATIONLOOP':'PrepareAnimationLoop',
  'PREPAREEFFECT':'PrepareEffect',
  'CASTANIMATION':'CastAnimation',
  'CASTTEXTEVENT':'CastTextEvent',
  'CASTEFFECT':'CastEffect',
  'CASTEFFECTTEXTEVENT':'CastEffectTextEvent',
  'TARGETEFFECT':'TargetEffect',
  'STORMEFFECT':'StormEffect',
  'IMPACTEFFECT':'ImpactEffect',
  'MEMORYCOST':'Memory Cost',
  'MAGICCOST':'Magic Cost',
  'SKILLBOOK':'Skillbook',
  'STEALTH':'Stealth',
  'PROJECTILESKILLS':'ProjectileSkills'
};

const SUMMON_NAMES = {
  'NAME':'Name',
  'USING':'Using',
  'SKILLTYPE':'SkillType',
  'LEVEL':'Level',
  'FORGAMEMASTER':'ForGameMaster',
  'ISENEMYSKILL':'IsEnemySkill',
  'ABILITY':'Ability',
  'TIER':'Tier',
  'REQUIREMENT':'Requirement',
  'ACTIONPOINTS':'ActionPoints',
  'COOLDOWN':'Cooldown',
  'AIFLAGS':'AIFlags',
  'LIFETIME':'Lifetime',
  'SUMMONLEVEL':'SummonLevel',
  'REQUIREMENTS':'Requirements',
  'MEMORIZATIONREQUIREMENTS':'MemorizationRequirements',
  'SKILLPROPERTIES':'SkillProperties',
  'AOECONDITIONS':'AoEConditions',
  'AREARADIUS':'AreaRadius',
  'MEMORYCOST':'Memory Cost',
  'MAGICCOST':'Magic Cost',
  'TEMPLATE':'Template',
  'TEMPLATEADVANCED':'TemplateAdvanced',
  'TEMPLATEOVERRIDE':'TemplateOverride',
  'TOTEM':'Totem',
  'LINKTELEPORTS':'LinkTeleports',
  'TARGETRADIUS':'TargetRadius',
  'SUMMONCOUNT':'SummonCount',
  'ICON':'Icon',
  'DISPLAYNAME':'DisplayName',
  'DESCRIPTION':'Description',
  'STATSDESCRIPTION':'StatsDescription',
  'STATSDESCRIPTIONPARAMS':'StatsDescriptionParams',
  'FXSCALE':'FXScale',
  'PREPAREANIMATIONINIT':'PrepareAnimationInit',
  'PREPAREANIMATIONLOOP':'PrepareAnimationLoop',
  'PREPAREEFFECT':'PrepareEffect',
  'CASTANIMATION':'CastAnimation',
  'CASTTEXTEVENT':'CastTextEvent',
  'CASTEFFECT':'CastEffect',
  'CASTEFFECTTEXTEVENT':'CastEffectTextEvent',
  'TARGETCASTEFFECT':'TargetCastEffect',
  'TARGETEFFECT':'TargetEffect',
  'SKILLBOOK':'Skillbook',
  'STEALTH':'Stealth',
  'AICALCULATIONSKILLOVERRIDE':'AiCalculationSkillOverride'
};

const TELEPORTATION_NAMES = {
  'NAME':'Name',
  'USING':'Using',
  'SKILLTYPE':'SkillType',
  'LEVEL':'Level',
  'FORGAMEMASTER':'ForGameMaster',
  'ISENEMYSKILL':'IsEnemySkill',
  'ABILITY':'Ability',
  'TIER':'Tier',
  'REQUIREMENT':'Requirement',
  'ACTIONPOINTS':'ActionPoints',
  'COOLDOWN':'Cooldown',
  'AIFLAGS':'AIFlags',
  'DAMAGE':'Damage',
  'DAMAGEMULTIPLIER':'Damage Multiplier',
  'DAMAGERANGE':'Damage Range',
  'DAMAGETYPE':'DamageType',
  'MEMORYCOST':'Memory Cost',
  'MAGICCOST':'Magic Cost',
  'TARGETRADIUS':'TargetRadius',
  'AREARADIUS':'AreaRadius',
  'DEATHTYPE':'DeathType',
  'HITRADIUS':'HitRadius',
  'HEIGHT':'Height',
  'ACCELERATION':'Acceleration',
  'TELEPORTDELAY':'TeleportDelay',
  'SKILLPROPERTIES':'SkillProperties',
  'TARGETCONDITIONS':'TargetConditions',
  'TELEPORTSELF':'TeleportSelf',
  'TELEPORTSURFACE':'TeleportSurface',
  'CANTARGETCHARACTERS':'CanTargetCharacters',
  'CANTARGETITEMS':'CanTargetItems',
  'CANTARGETTERRAIN':'CanTargetTerrain',
  'REQUIREMENTS':'Requirements',
  'MEMORIZATIONREQUIREMENTS':'MemorizationRequirements',
  'ICON':'Icon',
  'DISPLAYNAME':'DisplayName',
  'DESCRIPTION':'Description',
  'STATSDESCRIPTION':'StatsDescription',
  'STATSDESCRIPTIONPARAMS':'StatsDescriptionParams',
  'FXSCALE':'FXScale',
  'PREPAREANIMATIONINIT':'PrepareAnimationInit',
  'PREPAREANIMATIONLOOP':'PrepareAnimationLoop',
  'PREPAREEFFECT':'PrepareEffect',
  'CASTANIMATION':'CastAnimation',
  'CASTTEXTEVENT':'CastTextEvent',
  'CASTEFFECT':'CastEffect',
  'PREVIEWEFFECT':'PreviewEffect',
  'SELECTEDCHARACTEREFFECT':'SelectedCharacterEffect',
  'SELECTEDOBJECTEFFECT':'SelectedObjectEffect',
  'SELECTEDPOSITIONEFFECT':'SelectedPositionEffect',
  'DISAPPEAREFFECT':'DisappearEffect',
  'REAPPEAREFFECT':'ReappearEffect',
  'IMPACTEFFECT':'ImpactEffect',
  'IGNOREVISIONBLOCK':'IgnoreVisionBlock',
  'FORCEMOVE':'ForceMove',
  'STEALTH':'Stealth',
  'OVERRIDESKILLLEVEL':'OverrideSkillLevel'
};

const TORNADO_NAMES = {
  'NAME':'Name',
  'USING':'Using',
  'SKILLTYPE':'SkillType',
  'LEVEL':'Level',
  'FORGAMEMASTER':'ForGameMaster',
  'ISENEMYSKILL':'IsEnemySkill',
  'ABILITY':'Ability',
  'TIER':'Tier',
  'REQUIREMENT':'Requirement',
  'ACTIONPOINTS':'ActionPoints',
  'COOLDOWN':'Cooldown',
  'AIFLAGS':'AIFlags',
  'DAMAGE':'Damage',
  'DAMAGEMULTIPLIER':'Damage Multiplier',
  'DAMAGERANGE':'Damage Range',
  'DAMAGETYPE':'DamageType',
  'SKILLPROPERTIES':'SkillProperties',
  'TARGETRADIUS':'TargetRadius',
  'HITRADIUS':'HitRadius',
  'RANDOMPOINTS':'RandomPoints',
  'DEATHTYPE':'DeathType',
  'SURFACETYPE':'SurfaceType',
  'SURFACERADIUS':'SurfaceRadius',
  'SURFACELIFETIME':'SurfaceLifetime',
  'SURFACESTATUSCHANCE':'SurfaceStatusChance',
  'POINTSMAXOFFSET':'PointsMaxOffset',
  'REQUIREMENTS':'Requirements',
  'MEMORIZATIONREQUIREMENTS':'MemorizationRequirements',
  'ICON':'Icon',
  'DISPLAYNAME':'DisplayName',
  'DESCRIPTION':'Description',
  'STATSDESCRIPTION':'StatsDescription',
  'STATSDESCRIPTIONPARAMS':'StatsDescriptionParams',
  'FXSCALE':'FXScale',
  'PREPAREANIMATIONINIT':'PrepareAnimationInit',
  'PREPAREANIMATIONLOOP':'PrepareAnimationLoop',
  'PREPAREEFFECT':'PrepareEffect',
  'CASTANIMATION':'CastAnimation',
  'CASTTEXTEVENT':'CastTextEvent',
  'CASTEFFECT':'CastEffect',
  'CASTEFFECTTEXTEVENT':'CastEffectTextEvent',
  'TARGETEFFECT':'TargetEffect',
  'MEMORYCOST':'Memory Cost',
  'MAGICCOST':'Magic Cost',
  'CLEANSESTATUSES':'CleanseStatuses',
  'STATUSCLEARCHANCE':'StatusClearChance',
  'STEALTH':'Stealth'
};

const WALL_NAMES = {
  'NAME':'Name',
  'USING':'Using',
  'SKILLTYPE':'SkillType',
  'LEVEL':'Level',
  'FORGAMEMASTER':'ForGameMaster',
  'ISENEMYSKILL':'IsEnemySkill',
  'ABILITY':'Ability',
  'TIER':'Tier',
  'REQUIREMENT':'Requirement',
  'ACTIONPOINTS':'ActionPoints',
  'COOLDOWN':'Cooldown',
  'AIFLAGS':'AIFlags',
  'DAMAGE':'Damage',
  'DAMAGEMULTIPLIER':'Damage Multiplier',
  'DAMAGERANGE':'Damage Range',
  'DAMAGETYPE':'DamageType',
  'SKILLPROPERTIES':'SkillProperties',
  'TARGETRADIUS':'TargetRadius',
  'MAXDISTANCE':'MaxDistance',
  'DEATHTYPE':'DeathType',
  'LIFETIME':'Lifetime',
  'GROWSPEED':'GrowSpeed',
  'GROWTIMEOUT':'GrowTimeout',
  'SURFACETYPE':'SurfaceType',
  'TOTALSURFACECELLS':'TotalSurfaceCells',
  'SURFACEGROWSTEP':'SurfaceGrowStep',
  'SURFACEGROWINTERVAL':'SurfaceGrowInterval',
  'SURFACELIFETIME':'SurfaceLifetime',
  'SURFACESTATUSCHANCE':'SurfaceStatusChance',
  'ICON':'Icon',
  'DISPLAYNAME':'DisplayName',
  'DESCRIPTION':'Description',
  'STATSDESCRIPTION':'StatsDescription',
  'STATSDESCRIPTIONPARAMS':'StatsDescriptionParams',
  'FXSCALE':'FXScale',
  'PREPAREANIMATIONINIT':'PrepareAnimationInit',
  'PREPAREANIMATIONLOOP':'PrepareAnimationLoop',
  'PREPAREEFFECT':'PrepareEffect',
  'CASTANIMATION':'CastAnimation',
  'CASTTEXTEVENT':'CastTextEvent',
  'CASTEFFECT':'CastEffect',
  'CASTEFFECTTEXTEVENT':'CastEffectTextEvent',
  'SOURCETARGETEFFECT':'SourceTargetEffect',
  'TARGETTARGETEFFECT':'TargetTargetEffect',
  'TEMPLATE1':'Template1',
  'TEMPLATE2':'Template2',
  'TEMPLATE3':'Template3',
  'SPAWNEFFECT':'SpawnEffect',
  'MEMORYCOST':'Memory Cost',
  'MAGICCOST':'Magic Cost',
  'REQUIREMENTS':'Requirements',
  'MEMORIZATIONREQUIREMENTS':'MemorizationRequirements',
  'STEALTH':'Stealth',
  'PREVIEWEFFECT':'PreviewEffect'
};

const ZONE_NAMES = {
  'NAME':'Name',
  'USING':'Using',
  'SKILLTYPE':'SkillType',
  'LEVEL':'Level',
  'FORGAMEMASTER':'ForGameMaster',
  'ISENEMYSKILL':'IsEnemySkill',
  'ABILITY':'Ability',
  'TIER':'Tier',
  'REQUIREMENT':'Requirement',
  'ACTIONPOINTS':'ActionPoints',
  'COOLDOWN':'Cooldown',
  'AIFLAGS':'AIFlags',
  'DAMAGE':'Damage',
  'DAMAGEMULTIPLIER':'Damage Multiplier',
  'DAMAGERANGE':'Damage Range',
  'DAMAGETYPE':'DamageType',
  'SKILLPROPERTIES':'SkillProperties',
  'DEATHTYPE':'DeathType',
  'SURFACETYPE':'SurfaceType',
  'IGNORECURSED':'IgnoreCursed',
  'SURFACELIFETIME':'SurfaceLifetime',
  'SURFACESTATUSCHANCE':'SurfaceStatusChance',
  'SURFACEGROWSTEP':'SurfaceGrowStep',
  'SURFACEGROWINTERVAL':'SurfaceGrowInterval',
  'TARGETCONDITIONS':'TargetConditions',
  'USEWEAPONDAMAGE':'UseWeaponDamage',
  'USEWEAPONPROPERTIES':'UseWeaponProperties',
  'CANTARGETCHARACTERS':'CanTargetCharacters',
  'CANTARGETITEMS':'CanTargetItems',
  'ICON':'Icon',
  'DISPLAYNAME':'DisplayName',
  'DESCRIPTION':'Description',
  'STATSDESCRIPTION':'StatsDescription',
  'STATSDESCRIPTIONPARAMS':'StatsDescriptionParams',
  'FXSCALE':'FXScale',
  'PREPAREANIMATIONINIT':'PrepareAnimationInit',
  'PREPAREANIMATIONLOOP':'PrepareAnimationLoop',
  'PREPAREEFFECT':'PrepareEffect',
  'CASTANIMATION':'CastAnimation',
  'CASTTEXTEVENT':'CastTextEvent',
  'CASTEFFECT':'CastEffect',
  'CASTEFFECTTEXTEVENT':'CastEffectTextEvent',
  'MEMORYCOST':'Memory Cost',
  'MAGICCOST':'Magic Cost',
  'REQUIREMENTS':'Requirements',
  'MEMORIZATIONREQUIREMENTS':'MemorizationRequirements',
  'PUSHDISTANCE':'PushDistance',
  'STEALTH':'Stealth',
  'SHAPE':'Shape',
  'BACKSTART':'BackStart',
  'FRONTOFFSET':'FrontOffset',
  'RANGE':'Range',
  'BASE':'Base',
  'ANGLE':'Angle'
};

const SKILL_FIELDS = {
  'Name': (value) => ({ name: 'Name', type: 'NameStatObjectFieldDefinition', value}),
  'Using': (value) => ({ name: 'Using', type: 'BaseClassStatObjectFieldDefinition', value}),
  'SkillType': (value) => ({ name: 'SkillType', type: 'StringStatObjectFieldDefinition', value}),
  'Level': (value) => ({ name: 'Level', type: 'IntegerStatObjectFieldDefinition', value}),
  'ForGameMaster': (value) => ({ name: 'ForGameMaster', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'YesNo'}),
  'IsEnemySkill': (value) => ({ name: 'IsEnemySkill', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'YesNo'}),
  'Ability': (value) => ({ name: 'Ability', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'SkillAbility'}),
  'Tier': (value) => ({ name: 'Tier', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'SkillTier'}),
  'Requirement': (value) => ({ name: 'Requirement', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'SkillRequirement'}),
  'ActionPoints': (value) => ({ name: 'ActionPoints', type: 'IntegerStatObjectFieldDefinition', value}),
  'Cooldown': (value) => ({ name: 'Cooldown', type: 'IntegerStatObjectFieldDefinition', value}),
  'AIFlags': (value) => ({ name: 'AIFlags', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'AIFlags'}),
  'Damage': (value) => ({ name: 'Damage', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'DamageSourceType'}),
  'Damage Multiplier': (value) => ({ name: 'Damage Multiplier', type: 'IntegerStatObjectFieldDefinition', value}),
  'Damage Range': (value) => ({ name: 'Damage Range', type: 'IntegerStatObjectFieldDefinition', value}),
  'DamageType': (value) => ({ name: 'DamageType', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'Damage Type'}),
  'SkillProperties': (value) => ({ name: 'SkillProperties', type: 'StringStatObjectFieldDefinition', value}),
  'TargetRadius': (value) => ({ name: 'TargetRadius', type: 'IntegerStatObjectFieldDefinition', value}),
  'AddRangeFromAbility': (value) => ({ name: 'AddRangeFromAbility', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'Ability'}),
  'AreaRadius': (value) => ({ name: 'AreaRadius', type: 'IntegerStatObjectFieldDefinition', value}),
  'DeathType': (value) => ({ name: 'DeathType', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'Death Type'}),
  'ExplodeRadius': (value) => ({ name: 'ExplodeRadius', type: 'IntegerStatObjectFieldDefinition', value}),
  'CanTargetCharacters': (value) => ({ name: 'CanTargetCharacters', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'YesNo'}),
  'CanTargetItems': (value) => ({ name: 'CanTargetItems', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'YesNo'}),
  'CanTargetTerrain': (value) => ({ name: 'CanTargetTerrain', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'YesNo'}),
  'ForceTarget': (value) => ({ name: 'ForceTarget', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'YesNo'}),
  'AmountOfTargets': (value) => ({ name: 'AmountOfTargets', type: 'IntegerStatObjectFieldDefinition', value}),
  'AutoAim': (value) => ({ name: 'AutoAim', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'YesNo'}),
  'TargetConditions': (value) => ({ name: 'TargetConditions', type: 'StringStatObjectFieldDefinition', value}),
  'ForkingConditions': (value) => ({ name: 'ForkingConditions', type: 'StringStatObjectFieldDefinition', value}),
  'UseCharacterStats': (value) => ({ name: 'UseCharacterStats', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'YesNo'}),
  'UseWeaponDamage': (value) => ({ name: 'UseWeaponDamage', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'YesNo'}),
  'UseWeaponProperties': (value) => ({ name: 'UseWeaponProperties', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'YesNo'}),
  'ProjectileCount': (value) => ({ name: 'ProjectileCount', type: 'IntegerStatObjectFieldDefinition', value}),
  'ProjectileDelay': (value) => ({ name: 'ProjectileDelay', type: 'IntegerStatObjectFieldDefinition', value}),
  'Angle': (value) => ({ name: 'Angle', type: 'IntegerStatObjectFieldDefinition', value}),
  'Template': (value) => ({ name: 'Template', type: 'StringStatObjectFieldDefinition', value}),
  'IgnoreVisionBlock': (value) => ({ name: 'IgnoreVisionBlock', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'YesNo'}),
  'TemplateCheck': (value) => ({ name: 'TemplateCheck', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'CastCheckType'}),
  'ChanceToPierce': (value) => ({ name: 'ChanceToPierce', type: 'IntegerStatObjectFieldDefinition', value}),
  'MaxPierceCount': (value) => ({ name: 'MaxPierceCount', type: 'IntegerStatObjectFieldDefinition', value}),
  'MaxForkCount': (value) => ({ name: 'MaxForkCount', type: 'IntegerStatObjectFieldDefinition', value}),
  'ForkLevels': (value) => ({ name: 'ForkLevels', type: 'IntegerStatObjectFieldDefinition', value}),
  'ForkChance': (value) => ({ name: 'ForkChance', type: 'IntegerStatObjectFieldDefinition', value}),
  'Icon': (value) => ({ name: 'Icon', type: 'StringStatObjectFieldDefinition', value}),
  'DisplayName': (value) => ({ name: 'DisplayName', type: 'TranslatedStringStatObjectFieldDefinition', value}),
  'Description': (value) => ({ name: 'Description', type: 'TranslatedStringStatObjectFieldDefinition', value}),
  'StatsDescription': (value) => ({ name: 'StatsDescription', type: 'TranslatedStringStatObjectFieldDefinition', value}),
  'StatsDescriptionParams': (value) => ({ name: 'StatsDescriptionParams', type: 'StringStatObjectFieldDefinition', value}),
  'PrepareAnimationInit': (value) => ({ name: 'PrepareAnimationInit', type: 'StringStatObjectFieldDefinition', value}),
  'PrepareAnimationLoop': (value) => ({ name: 'PrepareAnimationLoop', type: 'StringStatObjectFieldDefinition', value}),
  'PrepareEffect': (value) => ({ name: 'PrepareEffect', type: 'StringStatObjectFieldDefinition', value}),
  'CastAnimation': (value) => ({ name: 'CastAnimation', type: 'StringStatObjectFieldDefinition', value}),
  'CastAnimationCheck': (value) => ({ name: 'CastAnimationCheck', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'CastCheckType'}),
  'CastTextEvent': (value) => ({ name: 'CastTextEvent', type: 'StringStatObjectFieldDefinition', value}),
  'CastEffect': (value) => ({ name: 'CastEffect', type: 'StringStatObjectFieldDefinition', value}),
  'PreviewEffect': (value) => ({ name: 'PreviewEffect', type: 'StringStatObjectFieldDefinition', value}),
  'Requirements': (value) => ({ name: 'Requirements', type: 'StringStatObjectFieldDefinition', value}),
  'MemorizationRequirements': (value) => ({ name: 'MemorizationRequirements', type: 'StringStatObjectFieldDefinition', value}),
  'Memory Cost': (value) => ({ name: 'Memory Cost', type: 'IntegerStatObjectFieldDefinition', value}),
  'Magic Cost': (value) => ({ name: 'Magic Cost', type: 'IntegerStatObjectFieldDefinition', value}),
  'DivideDamage': (value) => ({ name: 'DivideDamage', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'YesNo'}),
  'ProjectileTerrainOffset': (value) => ({ name: 'ProjectileTerrainOffset', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'YesNo'}),
  'MovingObject': (value) => ({ name: 'MovingObject', type: 'StringStatObjectFieldDefinition', value}),
  'ProjectileType': (value) => ({ name: 'ProjectileType', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'ProjectileType'}),
  'OverrideMinAP': (value) => ({ name: 'OverrideMinAP', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'YesNo'}),
  'Stealth': (value) => ({ name: 'Stealth', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'YesNo'}),
  'Stealth Damage Multiplier': (value) => ({ name: 'Stealth Damage Multiplier', type: 'IntegerStatObjectFieldDefinition', value}),
  'Distance Damage Multiplier': (value) => ({ name: 'Distance Damage Multiplier', type: 'IntegerStatObjectFieldDefinition', value}),
  'HeightOffset': (value) => ({ name: 'HeightOffset', type: 'IntegerStatObjectFieldDefinition', value}),
  'SpawnObject': (value) => ({ name: 'SpawnObject', type: 'StringStatObjectFieldDefinition', value}),
  'SpawnEffect': (value) => ({ name: 'SpawnEffect', type: 'StringStatObjectFieldDefinition', value}),
  'SpawnFXOverridesImpactFX': (value) => ({ name: 'SpawnFXOverridesImpactFX', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'YesNo'}),
  'SpawnLifetime': (value) => ({ name: 'SpawnLifetime', type: 'IntegerStatObjectFieldDefinition', value}),
  'AiCalculationSkillOverride': (value) => ({ name: 'AiCalculationSkillOverride', type: 'StringStatObjectFieldDefinition', value}),
  'AddWeaponRange': (value) => ({ name: 'AddWeaponRange', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'YesNo'}),
  'IsMelee': (value) => ({ name: 'IsMelee', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'YesNo'}),
  'AoEConditions': (value) => ({ name: 'AoEConditions', type: 'StringStatObjectFieldDefinition', value}),
  'FXScale': (value) => ({ name: 'FXScale', type: 'IntegerStatObjectFieldDefinition', value}),
  'CastSelfAnimation': (value) => ({ name: 'CastSelfAnimation', type: 'StringStatObjectFieldDefinition', value}),
  'WeaponBones': (value) => ({ name: 'WeaponBones', type: 'StringStatObjectFieldDefinition', value}),
  'TargetEffect': (value) => ({ name: 'TargetEffect', type: 'StringStatObjectFieldDefinition', value}),
  'TargetGroundEffect': (value) => ({ name: 'TargetGroundEffect', type: 'StringStatObjectFieldDefinition', value}),
  'PositionEffect': (value) => ({ name: 'PositionEffect', type: 'StringStatObjectFieldDefinition', value}),
  'BeamEffect': (value) => ({ name: 'BeamEffect', type: 'StringStatObjectFieldDefinition', value}),
  'SkillEffect': (value) => ({ name: 'SkillEffect', type: 'StringStatObjectFieldDefinition', value}),
  'CleanseStatuses': (value) => ({ name: 'CleanseStatuses', type: 'StringStatObjectFieldDefinition', value}),
  'StatusClearChance': (value) => ({ name: 'StatusClearChance', type: 'IntegerStatObjectFieldDefinition', value}),
  'Autocast': (value) => ({ name: 'Autocast', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'YesNo'}),
  'Range': (value) => ({ name: 'Range', type: 'IntegerStatObjectFieldDefinition', value}),
  'SurfaceType': (value) => ({ name: 'SurfaceType', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'Surface Type'}),
  'IgnoreCursed': (value) => ({ name: 'IgnoreCursed', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'YesNo'}),
  'SurfaceLifetime': (value) => ({ name: 'SurfaceLifetime', type: 'IntegerStatObjectFieldDefinition', value}),
  'SurfaceStatusChance': (value) => ({ name: 'SurfaceStatusChance', type: 'IntegerStatObjectFieldDefinition', value}),
  'SurfaceGrowStep': (value) => ({ name: 'SurfaceGrowStep', type: 'IntegerStatObjectFieldDefinition', value}),
  'SurfaceGrowInterval': (value) => ({ name: 'SurfaceGrowInterval', type: 'IntegerStatObjectFieldDefinition', value}),
  'CastEffectTextEvent': (value) => ({ name: 'CastEffectTextEvent', type: 'StringStatObjectFieldDefinition', value}),
  'PushDistance': (value) => ({ name: 'PushDistance', type: 'IntegerStatObjectFieldDefinition', value}),
  'BackStart': (value) => ({ name: 'BackStart', type: 'IntegerStatObjectFieldDefinition', value}),
  'FrontOffset': (value) => ({ name: 'FrontOffset', type: 'IntegerStatObjectFieldDefinition', value}),
  'Lifetime': (value) => ({ name: 'Lifetime', type: 'IntegerStatObjectFieldDefinition', value}),
  'AuraSelf': (value) => ({ name: 'AuraSelf', type: 'StringStatObjectFieldDefinition', value}),
  'AuraAllies': (value) => ({ name: 'AuraAllies', type: 'StringStatObjectFieldDefinition', value}),
  'AuraNeutrals': (value) => ({ name: 'AuraNeutrals', type: 'StringStatObjectFieldDefinition', value}),
  'AuraEnemies': (value) => ({ name: 'AuraEnemies', type: 'StringStatObjectFieldDefinition', value}),
  'AuraItems': (value) => ({ name: 'AuraItems', type: 'StringStatObjectFieldDefinition', value}),
  'DomeEffect': (value) => ({ name: 'DomeEffect', type: 'StringStatObjectFieldDefinition', value}),
  'HitRadius': (value) => ({ name: 'HitRadius', type: 'IntegerStatObjectFieldDefinition', value}),
  'Damage On Jump': (value) => ({ name: 'Damage On Jump', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'YesNo'}),
  'Damage On Landing': (value) => ({ name: 'Damage On Landing', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'YesNo'}),
  'TeleportTextEvent': (value) => ({ name: 'TeleportTextEvent', type: 'StringStatObjectFieldDefinition', value}),
  'LandingEffect': (value) => ({ name: 'LandingEffect', type: 'StringStatObjectFieldDefinition', value}),
  'MaxAttacks': (value) => ({ name: 'MaxAttacks', type: 'IntegerStatObjectFieldDefinition', value}),
  'NextAttackChance': (value) => ({ name: 'NextAttackChance', type: 'IntegerStatObjectFieldDefinition', value}),
  'NextAttackChanceDivider': (value) => ({ name: 'NextAttackChanceDivider', type: 'IntegerStatObjectFieldDefinition', value}),
  'EndPosRadius': (value) => ({ name: 'EndPosRadius', type: 'IntegerStatObjectFieldDefinition', value}),
  'JumpDelay': (value) => ({ name: 'JumpDelay', type: 'IntegerStatObjectFieldDefinition', value}),
  'PrepareEffectBone': (value) => ({ name: 'PrepareEffectBone', type: 'StringStatObjectFieldDefinition', value}),
  'MaleImpactEffects': (value) => ({ name: 'MaleImpactEffects', type: 'StringStatObjectFieldDefinition', value}),
  'FemaleImpactEffects': (value) => ({ name: 'FemaleImpactEffects', type: 'StringStatObjectFieldDefinition', value}),
  'ReappearEffect': (value) => ({ name: 'ReappearEffect', type: 'StringStatObjectFieldDefinition', value}),
  'ReappearEffectTextEvent': (value) => ({ name: 'ReappearEffectTextEvent', type: 'StringStatObjectFieldDefinition', value}),
  'SurfaceRadius': (value) => ({ name: 'SurfaceRadius', type: 'IntegerStatObjectFieldDefinition', value}),
  'MaxDistance': (value) => ({ name: 'MaxDistance', type: 'IntegerStatObjectFieldDefinition', value}),
  'Offset': (value) => ({ name: 'Offset', type: 'IntegerStatObjectFieldDefinition', value}),
  'Height': (value) => ({ name: 'Height', type: 'IntegerStatObjectFieldDefinition', value}),
  'TravelSpeed': (value) => ({ name: 'TravelSpeed', type: 'IntegerStatObjectFieldDefinition', value}),
  'FlyEffect': (value) => ({ name: 'FlyEffect', type: 'StringStatObjectFieldDefinition', value}),
  'ImpactEffect': (value) => ({ name: 'ImpactEffect', type: 'StringStatObjectFieldDefinition', value}),
  'Skillbook': (value) => ({ name: 'Skillbook', type: 'StringStatObjectFieldDefinition', value}),
  'StrikeCount': (value) => ({ name: 'StrikeCount', type: 'IntegerStatObjectFieldDefinition', value}),
  'StrikeDelay': (value) => ({ name: 'StrikeDelay', type: 'IntegerStatObjectFieldDefinition', value}),
  'OverrideSkillLevel': (value) => ({ name: 'OverrideSkillLevel', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'YesNo'}),
  'TargetProjectiles': (value) => ({ name: 'TargetProjectiles', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'YesNo'}),
  'SingleSource': (value) => ({ name: 'SingleSource', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'YesNo'}),
  'Distribution': (value) => ({ name: 'Distribution', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'ProjectileDistribution'}),
  'Shuffle': (value) => ({ name: 'Shuffle', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'YesNo'}),
  'PreviewStrikeHits': (value) => ({ name: 'PreviewStrikeHits', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'YesNo'}),
  'TotalSurfaceCells': (value) => ({ name: 'TotalSurfaceCells', type: 'IntegerStatObjectFieldDefinition', value}),
  'SurfaceMinSpawnRadius': (value) => ({ name: 'SurfaceMinSpawnRadius', type: 'IntegerStatObjectFieldDefinition', value}),
  'ShockWaveDuration': (value) => ({ name: 'ShockWaveDuration', type: 'IntegerStatObjectFieldDefinition', value}),
  'MinSurfaces': (value) => ({ name: 'MinSurfaces', type: 'IntegerStatObjectFieldDefinition', value}),
  'MaxSurfaces': (value) => ({ name: 'MaxSurfaces', type: 'IntegerStatObjectFieldDefinition', value}),
  'RainEffect': (value) => ({ name: 'RainEffect', type: 'StringStatObjectFieldDefinition', value}),
  'Atmosphere': (value) => ({ name: 'Atmosphere', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'AtmosphereType'}),
  'ConsequencesStartTime': (value) => ({ name: 'ConsequencesStartTime', type: 'IntegerStatObjectFieldDefinition', value}),
  'ConsequencesDuration': (value) => ({ name: 'ConsequencesDuration', type: 'IntegerStatObjectFieldDefinition', value}),
  'ContinueOnKill': (value) => ({ name: 'ContinueOnKill', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'YesNo'}),
  'ContinueEffect': (value) => ({ name: 'ContinueEffect', type: 'StringStatObjectFieldDefinition', value}),
  'TargetCastEffect': (value) => ({ name: 'TargetCastEffect', type: 'StringStatObjectFieldDefinition', value}),
  'TargetHitEffect': (value) => ({ name: 'TargetHitEffect', type: 'StringStatObjectFieldDefinition', value}),
  'StartTextEvent': (value) => ({ name: 'StartTextEvent', type: 'StringStatObjectFieldDefinition', value}),
  'StopTextEvent': (value) => ({ name: 'StopTextEvent', type: 'StringStatObjectFieldDefinition', value}),
  'HitEffect': (value) => ({ name: 'HitEffect', type: 'StringStatObjectFieldDefinition', value}),
  'PushPullEffect': (value) => ({ name: 'PushPullEffect', type: 'StringStatObjectFieldDefinition', value}),
  'MinHitsPerTurn': (value) => ({ name: 'MinHitsPerTurn', type: 'IntegerStatObjectFieldDefinition', value}),
  'MaxHitsPerTurn': (value) => ({ name: 'MaxHitsPerTurn', type: 'IntegerStatObjectFieldDefinition', value}),
  'HitDelay': (value) => ({ name: 'HitDelay', type: 'IntegerStatObjectFieldDefinition', value}),
  'StormEffect': (value) => ({ name: 'StormEffect', type: 'StringStatObjectFieldDefinition', value}),
  'ProjectileSkills': (value) => ({ name: 'ProjectileSkills', type: 'StringStatObjectFieldDefinition', value}),
  'SummonLevel': (value) => ({ name: 'SummonLevel', type: 'IntegerStatObjectFieldDefinition', value}),
  'TemplateAdvanced': (value) => ({ name: 'TemplateAdvanced', type: 'StringStatObjectFieldDefinition', value}),
  'TemplateOverride': (value) => ({ name: 'TemplateOverride', type: 'StringStatObjectFieldDefinition', value}),
  'Totem': (value) => ({ name: 'Totem', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'YesNo'}),
  'LinkTeleports': (value) => ({ name: 'LinkTeleports', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'YesNo'}),
  'SummonCount': (value) => ({ name: 'SummonCount', type: 'IntegerStatObjectFieldDefinition', value}),
  'Acceleration': (value) => ({ name: 'Acceleration', type: 'IntegerStatObjectFieldDefinition', value}),
  'TeleportDelay': (value) => ({ name: 'TeleportDelay', type: 'IntegerStatObjectFieldDefinition', value}),
  'TeleportSelf': (value) => ({ name: 'TeleportSelf', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'YesNo'}),
  'TeleportSurface': (value) => ({ name: 'TeleportSurface', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'YesNo'}),
  'SelectedCharacterEffect': (value) => ({ name: 'SelectedCharacterEffect', type: 'StringStatObjectFieldDefinition', value}),
  'SelectedObjectEffect': (value) => ({ name: 'SelectedObjectEffect', type: 'StringStatObjectFieldDefinition', value}),
  'SelectedPositionEffect': (value) => ({ name: 'SelectedPositionEffect', type: 'StringStatObjectFieldDefinition', value}),
  'DisappearEffect': (value) => ({ name: 'DisappearEffect', type: 'StringStatObjectFieldDefinition', value}),
  'ForceMove': (value) => ({ name: 'ForceMove', type: 'EnumerationStatObjectFieldDefinition', value, 'enumeration_type_name': 'YesNo'}),
  'RandomPoints': (value) => ({ name: 'RandomPoints', type: 'IntegerStatObjectFieldDefinition', value}),
  'PointsMaxOffset': (value) => ({ name: 'PointsMaxOffset', type: 'IntegerStatObjectFieldDefinition', value}),
  'GrowSpeed': (value) => ({ name: 'GrowSpeed', type: 'IntegerStatObjectFieldDefinition', value}),
  'GrowTimeout': (value) => ({ name: 'GrowTimeout', type: 'IntegerStatObjectFieldDefinition', value}),
  'SourceTargetEffect': (value) => ({ name: 'SourceTargetEffect', type: 'StringStatObjectFieldDefinition', value}),
  'TargetTargetEffect': (value) => ({ name: 'TargetTargetEffect', type: 'StringStatObjectFieldDefinition', value}),
  'Template1': (value) => ({ name: 'Template1', type: 'StringStatObjectFieldDefinition', value}),
  'Template2': (value) => ({ name: 'Template2', type: 'StringStatObjectFieldDefinition', value}),
  'Template3': (value) => ({ name: 'Template3', type: 'StringStatObjectFieldDefinition', value}),
  'Shape': (value) => ({ name: 'Shape', type: 'StringStatObjectFieldDefinition', value}),
  'Base': (value) => ({ name: 'Base', type: 'IntegerStatObjectFieldDefinition', value}),
};

module.exports = {
  SKILL_FIELD_NAMES,
  SKILL_FIELDS,
  PROJECTILE_NAMES,
  TARGET_NAMES,
  CONE_NAMES,
  DOME_NAMES,
  JUMP_NAMES,
  MULTISTRIKE_NAMES,
  PATH_NAMES,
  PROJECTILESTRIKE_NAMES,
  QUAKE_NAMES,
  RAIN_NAMES,
  RUSH_NAMES,
  SHOUT_NAMES,
  STORM_NAMES,
  SUMMON_NAMES,
  TELEPORTATION_NAMES,
  TORNADO_NAMES,
  WALL_NAMES,
  ZONE_NAMES,
};